sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '0.10'
before_install:
  - npm i -g npm@^2.0.0
after_success:
  - npm run semantic-release
